CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO issues (title, status)
VALUES
  ('Cannot log in after password reset', 'OPEN'),
  ('Intermittent 502 from reverse proxy', 'INVESTIGATING'),
  ('UI freezes when loading large project', 'OPEN');
